export const ADD_LINK = 'ADD_LINK'
export const REMOVE_LINK = 'REMOVE_LINK '
export const CHANGE_LINK_PRIORITY = 'CHANGE_LINK_PRIORITY'
export const CHANGE_MOST_USED_COUNT = 'CHANGE_MOST_USED_COUNT'

export default {
  ADD_LINK,
  REMOVE_LINK,
  CHANGE_LINK_PRIORITY,
  CHANGE_MOST_USED_COUNT
}
