// UI
export const SET_PLATFORM = 'SET_PLATFORM'
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

// PROFILE
export const SETUP_USER_PROFILE = 'SETUP_USER_PROFILE'

// SCHEDULE
export const SETUP_SCHEDULE = 'SETUP_SCHEDULE'
export const REQUEST_SCHEDULE = 'REQUEST_SCHEDULE'
